//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.34209 版自动生成。
// 
#pragma warning disable 1591

namespace Business.MES_LK {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MES_LK_Integration_ServicesSoap", Namespace="http://tempuri.org/")]
    public partial class MES_LK_Integration_Services : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Receive_LKDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback transgetCPKCOperationCompleted;
        
        private System.Threading.SendOrPostCallback transSTOCKOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback transYLTLOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback transFLXHOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback Mes_WL_GDXXOperationCompleted;
        
        private System.Threading.SendOrPostCallback PackWorkOrderStart_EndOperationCompleted;
        
        private System.Threading.SendOrPostCallback SCZX_MES_OutPutOperationCompleted;
        
        private System.Threading.SendOrPostCallback PackProduceAmountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MES_LK_Integration_Services() {
            this.Url = global::Business.Properties.Settings.Default.Business_MES_LK_MES_LK_Integration_Services;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Receive_LKDataCompletedEventHandler Receive_LKDataCompleted;
        
        /// <remarks/>
        public event transgetCPKCCompletedEventHandler transgetCPKCCompleted;
        
        /// <remarks/>
        public event transSTOCKOrderCompletedEventHandler transSTOCKOrderCompleted;
        
        /// <remarks/>
        public event transYLTLOrderCompletedEventHandler transYLTLOrderCompleted;
        
        /// <remarks/>
        public event transFLXHOrderCompletedEventHandler transFLXHOrderCompleted;
        
        /// <remarks/>
        public event Mes_WL_GDXXCompletedEventHandler Mes_WL_GDXXCompleted;
        
        /// <remarks/>
        public event PackWorkOrderStart_EndCompletedEventHandler PackWorkOrderStart_EndCompleted;
        
        /// <remarks/>
        public event SCZX_MES_OutPutCompletedEventHandler SCZX_MES_OutPutCompleted;
        
        /// <remarks/>
        public event PackProduceAmountCompletedEventHandler PackProduceAmountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Receive_LKData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Receive_LKData(string xml) {
            object[] results = this.Invoke("Receive_LKData", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Receive_LKDataAsync(string xml) {
            this.Receive_LKDataAsync(xml, null);
        }
        
        /// <remarks/>
        public void Receive_LKDataAsync(string xml, object userState) {
            if ((this.Receive_LKDataOperationCompleted == null)) {
                this.Receive_LKDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReceive_LKDataOperationCompleted);
            }
            this.InvokeAsync("Receive_LKData", new object[] {
                        xml}, this.Receive_LKDataOperationCompleted, userState);
        }
        
        private void OnReceive_LKDataOperationCompleted(object arg) {
            if ((this.Receive_LKDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Receive_LKDataCompleted(this, new Receive_LKDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/transgetCPKC", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string transgetCPKC() {
            object[] results = this.Invoke("transgetCPKC", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transgetCPKCAsync() {
            this.transgetCPKCAsync(null);
        }
        
        /// <remarks/>
        public void transgetCPKCAsync(object userState) {
            if ((this.transgetCPKCOperationCompleted == null)) {
                this.transgetCPKCOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransgetCPKCOperationCompleted);
            }
            this.InvokeAsync("transgetCPKC", new object[0], this.transgetCPKCOperationCompleted, userState);
        }
        
        private void OntransgetCPKCOperationCompleted(object arg) {
            if ((this.transgetCPKCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transgetCPKCCompleted(this, new transgetCPKCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/transSTOCKOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string transSTOCKOrder() {
            object[] results = this.Invoke("transSTOCKOrder", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transSTOCKOrderAsync() {
            this.transSTOCKOrderAsync(null);
        }
        
        /// <remarks/>
        public void transSTOCKOrderAsync(object userState) {
            if ((this.transSTOCKOrderOperationCompleted == null)) {
                this.transSTOCKOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransSTOCKOrderOperationCompleted);
            }
            this.InvokeAsync("transSTOCKOrder", new object[0], this.transSTOCKOrderOperationCompleted, userState);
        }
        
        private void OntransSTOCKOrderOperationCompleted(object arg) {
            if ((this.transSTOCKOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transSTOCKOrderCompleted(this, new transSTOCKOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/transYLTLOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string transYLTLOrder() {
            object[] results = this.Invoke("transYLTLOrder", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transYLTLOrderAsync() {
            this.transYLTLOrderAsync(null);
        }
        
        /// <remarks/>
        public void transYLTLOrderAsync(object userState) {
            if ((this.transYLTLOrderOperationCompleted == null)) {
                this.transYLTLOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransYLTLOrderOperationCompleted);
            }
            this.InvokeAsync("transYLTLOrder", new object[0], this.transYLTLOrderOperationCompleted, userState);
        }
        
        private void OntransYLTLOrderOperationCompleted(object arg) {
            if ((this.transYLTLOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transYLTLOrderCompleted(this, new transYLTLOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/transFLXHOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string transFLXHOrder() {
            object[] results = this.Invoke("transFLXHOrder", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void transFLXHOrderAsync() {
            this.transFLXHOrderAsync(null);
        }
        
        /// <remarks/>
        public void transFLXHOrderAsync(object userState) {
            if ((this.transFLXHOrderOperationCompleted == null)) {
                this.transFLXHOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OntransFLXHOrderOperationCompleted);
            }
            this.InvokeAsync("transFLXHOrder", new object[0], this.transFLXHOrderOperationCompleted, userState);
        }
        
        private void OntransFLXHOrderOperationCompleted(object arg) {
            if ((this.transFLXHOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.transFLXHOrderCompleted(this, new transFLXHOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Mes_WL_GDXX", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Mes_WL_GDXX(string[] orderList, string operaterID) {
            object[] results = this.Invoke("Mes_WL_GDXX", new object[] {
                        orderList,
                        operaterID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Mes_WL_GDXXAsync(string[] orderList, string operaterID) {
            this.Mes_WL_GDXXAsync(orderList, operaterID, null);
        }
        
        /// <remarks/>
        public void Mes_WL_GDXXAsync(string[] orderList, string operaterID, object userState) {
            if ((this.Mes_WL_GDXXOperationCompleted == null)) {
                this.Mes_WL_GDXXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMes_WL_GDXXOperationCompleted);
            }
            this.InvokeAsync("Mes_WL_GDXX", new object[] {
                        orderList,
                        operaterID}, this.Mes_WL_GDXXOperationCompleted, userState);
        }
        
        private void OnMes_WL_GDXXOperationCompleted(object arg) {
            if ((this.Mes_WL_GDXXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Mes_WL_GDXXCompleted(this, new Mes_WL_GDXXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PackWorkOrderStart_End", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PackWorkOrderStart_End(string wo, string state) {
            object[] results = this.Invoke("PackWorkOrderStart_End", new object[] {
                        wo,
                        state});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PackWorkOrderStart_EndAsync(string wo, string state) {
            this.PackWorkOrderStart_EndAsync(wo, state, null);
        }
        
        /// <remarks/>
        public void PackWorkOrderStart_EndAsync(string wo, string state, object userState) {
            if ((this.PackWorkOrderStart_EndOperationCompleted == null)) {
                this.PackWorkOrderStart_EndOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPackWorkOrderStart_EndOperationCompleted);
            }
            this.InvokeAsync("PackWorkOrderStart_End", new object[] {
                        wo,
                        state}, this.PackWorkOrderStart_EndOperationCompleted, userState);
        }
        
        private void OnPackWorkOrderStart_EndOperationCompleted(object arg) {
            if ((this.PackWorkOrderStart_EndCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PackWorkOrderStart_EndCompleted(this, new PackWorkOrderStart_EndCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SCZX_MES_OutPut", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SCZX_MES_OutPut(string xml) {
            object[] results = this.Invoke("SCZX_MES_OutPut", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SCZX_MES_OutPutAsync(string xml) {
            this.SCZX_MES_OutPutAsync(xml, null);
        }
        
        /// <remarks/>
        public void SCZX_MES_OutPutAsync(string xml, object userState) {
            if ((this.SCZX_MES_OutPutOperationCompleted == null)) {
                this.SCZX_MES_OutPutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSCZX_MES_OutPutOperationCompleted);
            }
            this.InvokeAsync("SCZX_MES_OutPut", new object[] {
                        xml}, this.SCZX_MES_OutPutOperationCompleted, userState);
        }
        
        private void OnSCZX_MES_OutPutOperationCompleted(object arg) {
            if ((this.SCZX_MES_OutPutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SCZX_MES_OutPutCompleted(this, new SCZX_MES_OutPutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PackProduceAmount", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PackProduceAmount(string date) {
            object[] results = this.Invoke("PackProduceAmount", new object[] {
                        date});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PackProduceAmountAsync(string date) {
            this.PackProduceAmountAsync(date, null);
        }
        
        /// <remarks/>
        public void PackProduceAmountAsync(string date, object userState) {
            if ((this.PackProduceAmountOperationCompleted == null)) {
                this.PackProduceAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPackProduceAmountOperationCompleted);
            }
            this.InvokeAsync("PackProduceAmount", new object[] {
                        date}, this.PackProduceAmountOperationCompleted, userState);
        }
        
        private void OnPackProduceAmountOperationCompleted(object arg) {
            if ((this.PackProduceAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PackProduceAmountCompleted(this, new PackProduceAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Receive_LKDataCompletedEventHandler(object sender, Receive_LKDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Receive_LKDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Receive_LKDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void transgetCPKCCompletedEventHandler(object sender, transgetCPKCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transgetCPKCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transgetCPKCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void transSTOCKOrderCompletedEventHandler(object sender, transSTOCKOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transSTOCKOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transSTOCKOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void transYLTLOrderCompletedEventHandler(object sender, transYLTLOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transYLTLOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transYLTLOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void transFLXHOrderCompletedEventHandler(object sender, transFLXHOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class transFLXHOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal transFLXHOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void Mes_WL_GDXXCompletedEventHandler(object sender, Mes_WL_GDXXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Mes_WL_GDXXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Mes_WL_GDXXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void PackWorkOrderStart_EndCompletedEventHandler(object sender, PackWorkOrderStart_EndCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackWorkOrderStart_EndCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PackWorkOrderStart_EndCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void SCZX_MES_OutPutCompletedEventHandler(object sender, SCZX_MES_OutPutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SCZX_MES_OutPutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SCZX_MES_OutPutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void PackProduceAmountCompletedEventHandler(object sender, PackProduceAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackProduceAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PackProduceAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591